### ISSUE TITLE
US02 - Envoyer mon message mise en forme dans des bulles Rainbow

### ISSUE THREAD

**Issue by Vladimir9595** [Info-Broadcaster/backend#8]
### US02: Envoyer mon message mise en forme dans des bulles Rainbow
**En tant que :** utilisateur de Rainbow
**Je souhaite :** une fois mon lien envoyé vers Broadcaster, je peux envoyer mon message vers mes bulles automatiquement sans copier coller
**Afin que :** d'éviter d'ouvrir deux applications en même temps

**Comment by Vladimir9595** [comment]
This issue is addressed in commit [feat/bubble-message-route](https://github.com/Info-Broadcaster/Backend/commit/952897bdfea31ce56567c572e0f5c98e9b4e7248)

**Comment by WRKT** [comment]
Testé sans l'intégration de la logique de connexion.

**Comment by WRKT** [comment]
Suite à la refacto, revoir le constructeur Rainbow dans sendMessageToBubbles avant clos.

**Comment by WRKT** [comment]
fix and improved by @Nerlake. 
Closed issue.
