### ISSUE TITLE
US06 - Adapter le texte en fonction du public ciblé (méca, astronomie, littérature etc...)

### ISSUE THREAD

**Issue by Vladimir9595** [Info-Broadcaster/backend#9]
### US06: Adapter le texte en fonction du public ciblé (méca, astronomie, littérature, ...)

**En tant que:** utilisateur de Broadcaster
**Je souhaite que:** le texte soit adapté en fonction de la bulle ciblé
**Afin que :** les lecteurs comprennent mieux et soit plus intéréssé

**Comment by WRKT** [comment]
Issue imbriqué par l'User story #7 .
Duplication, feature abandonné.
